2024-04-26 08:40:00,560 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-26 08:40:00,564 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Configure stats pid to 22507
2024-04-26 08:40:00,565 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Loading settings from /Users/jasonokoro/.config/wandb/settings
2024-04-26 08:40:00,565 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Loading settings from /Users/jasonokoro/Desktop/proyectos/nerf/wandb/settings
2024-04-26 08:40:00,565 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-26 08:40:00,566 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-26 08:40:00,566 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-26 08:40:00,567 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-26 08:40:00,568 INFO    MainThread:22507 [wandb_init.py:_log_setup():521] Logging user logs to /Users/jasonokoro/Desktop/proyectos/nerf/wandb/run-20240426_084000-5l8dw1cy/logs/debug.log
2024-04-26 08:40:00,570 INFO    MainThread:22507 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/jasonokoro/Desktop/proyectos/nerf/wandb/run-20240426_084000-5l8dw1cy/logs/debug-internal.log
2024-04-26 08:40:00,571 INFO    MainThread:22507 [wandb_init.py:_jupyter_setup():467] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x2df09e300>
2024-04-26 08:40:00,572 INFO    MainThread:22507 [wandb_init.py:init():561] calling init triggers
2024-04-26 08:40:00,573 INFO    MainThread:22507 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'name': 'initial-run', 'batch_size': 4096, 'initial_lr': 0.0005, 'final_lr': 5e-05, 'num_epochs': 10, 'tn': 0, 'tf': 1, 'Nc': 64, 'Nf': 128}
2024-04-26 08:40:00,576 INFO    MainThread:22507 [wandb_init.py:init():586] re-initializing run, found existing run on stack: pkt6jpyq
2024-04-26 08:40:00,609 INFO    MainThread:22507 [wandb_run.py:_finish():2064] finishing run 11785_group51/nerf/pkt6jpyq
2024-04-26 08:40:00,610 INFO    MainThread:22507 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-04-26 08:40:00,612 INFO    MainThread:22507 [wandb_run.py:_restore():2287] restore
2024-04-26 08:40:00,613 INFO    MainThread:22507 [wandb_run.py:_restore():2293] restore done
2024-04-26 08:40:06,316 INFO    MainThread:22507 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-04-26 08:40:06,317 INFO    MainThread:22507 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-04-26 08:40:06,375 INFO    MainThread:22507 [wandb_run.py:_footer_sync_info():3895] logging synced files
2024-04-26 08:40:06,611 INFO    MainThread:22507 [wandb_init.py:init():611] starting backend
2024-04-26 08:40:06,612 INFO    MainThread:22507 [wandb_init.py:init():615] setting up manager
2024-04-26 08:40:06,628 INFO    MainThread:22507 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-04-26 08:40:06,632 INFO    MainThread:22507 [wandb_init.py:init():623] backend started and connected
2024-04-26 08:40:06,682 INFO    MainThread:22507 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-26 08:40:06,683 INFO    MainThread:22507 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-26 08:40:06,685 INFO    MainThread:22507 [wandb_init.py:init():715] updated telemetry
2024-04-26 08:40:06,786 INFO    MainThread:22507 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-26 08:40:07,619 ERROR   MainThread:22507 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-26 08:40:07,759 ERROR   MainThread:22507 [wandb_init.py:init():1199] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-26 08:40:27,822 INFO    MainThread:22507 [wandb_settings.py:_apply_login():1943] Applying login settings: {}
2024-04-26 08:40:27,863 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-26 08:40:27,864 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Configure stats pid to 22507
2024-04-26 08:40:27,864 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Loading settings from /Users/jasonokoro/.config/wandb/settings
2024-04-26 08:40:27,864 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Loading settings from /Users/jasonokoro/Desktop/proyectos/nerf/wandb/settings
2024-04-26 08:40:27,865 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-26 08:40:27,865 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-26 08:40:27,865 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-26 08:40:27,865 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-26 08:40:27,871 INFO    MainThread:22507 [wandb_init.py:_log_setup():521] Logging user logs to /Users/jasonokoro/Desktop/proyectos/nerf/wandb/run-20240426_084027-cx6rbmil/logs/debug.log
2024-04-26 08:40:27,871 INFO    MainThread:22507 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/jasonokoro/Desktop/proyectos/nerf/wandb/run-20240426_084027-cx6rbmil/logs/debug-internal.log
2024-04-26 08:40:27,872 INFO    MainThread:22507 [wandb_init.py:init():561] calling init triggers
2024-04-26 08:40:27,872 INFO    MainThread:22507 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'name': 'initial-run', 'batch_size': 4096, 'initial_lr': 0.0005, 'final_lr': 5e-05, 'num_epochs': 10, 'tn': 0, 'tf': 1, 'Nc': 64, 'Nf': 128}
2024-04-26 08:40:27,873 INFO    MainThread:22507 [wandb_init.py:init():611] starting backend
2024-04-26 08:40:27,873 INFO    MainThread:22507 [wandb_init.py:init():615] setting up manager
2024-04-26 08:40:27,880 INFO    MainThread:22507 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-04-26 08:40:27,888 INFO    MainThread:22507 [wandb_init.py:init():623] backend started and connected
2024-04-26 08:40:27,907 INFO    MainThread:22507 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-26 08:40:27,908 INFO    MainThread:22507 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-26 08:40:27,909 INFO    MainThread:22507 [wandb_init.py:init():715] updated telemetry
2024-04-26 08:40:28,005 INFO    MainThread:22507 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-26 08:40:28,367 ERROR   MainThread:22507 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-26 08:40:28,444 ERROR   MainThread:22507 [wandb_init.py:init():1199] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-26 08:41:51,235 INFO    MainThread:22507 [wandb_settings.py:_apply_login():1943] Applying login settings: {}
2024-04-26 08:41:51,352 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-26 08:41:51,353 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Configure stats pid to 22507
2024-04-26 08:41:51,353 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Loading settings from /Users/jasonokoro/.config/wandb/settings
2024-04-26 08:41:51,353 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Loading settings from /Users/jasonokoro/Desktop/proyectos/nerf/wandb/settings
2024-04-26 08:41:51,354 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-26 08:41:51,355 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-26 08:41:51,356 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-26 08:41:51,357 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-26 08:41:51,358 INFO    MainThread:22507 [wandb_init.py:_log_setup():521] Logging user logs to /Users/jasonokoro/Desktop/proyectos/nerf/wandb/run-20240426_084151-rz42bqb4/logs/debug.log
2024-04-26 08:41:51,363 INFO    MainThread:22507 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/jasonokoro/Desktop/proyectos/nerf/wandb/run-20240426_084151-rz42bqb4/logs/debug-internal.log
2024-04-26 08:41:51,364 INFO    MainThread:22507 [wandb_init.py:init():561] calling init triggers
2024-04-26 08:41:51,366 INFO    MainThread:22507 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'name': 'initial-run', 'batch_size': 4096, 'initial_lr': 0.0005, 'final_lr': 5e-05, 'num_epochs': 10, 'tn': 0, 'tf': 1, 'Nc': 64, 'Nf': 128}
2024-04-26 08:41:51,369 INFO    MainThread:22507 [wandb_init.py:init():611] starting backend
2024-04-26 08:41:51,369 INFO    MainThread:22507 [wandb_init.py:init():615] setting up manager
2024-04-26 08:41:51,404 INFO    MainThread:22507 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-04-26 08:41:51,412 INFO    MainThread:22507 [wandb_init.py:init():623] backend started and connected
2024-04-26 08:41:51,576 INFO    MainThread:22507 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-26 08:41:51,576 INFO    MainThread:22507 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-26 08:41:51,577 INFO    MainThread:22507 [wandb_init.py:init():715] updated telemetry
2024-04-26 08:41:51,728 INFO    MainThread:22507 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-26 08:42:05,422 WARNING MainThread:22507 [wandb_init.py:init():1203] interrupted
Traceback (most recent call last):
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 751, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-04-26 08:42:08,625 INFO    MainThread:22507 [wandb_settings.py:_apply_login():1943] Applying login settings: {}
2024-04-26 08:42:08,682 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-26 08:42:08,683 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Configure stats pid to 22507
2024-04-26 08:42:08,683 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Loading settings from /Users/jasonokoro/.config/wandb/settings
2024-04-26 08:42:08,684 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Loading settings from /Users/jasonokoro/Desktop/proyectos/nerf/wandb/settings
2024-04-26 08:42:08,685 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-26 08:42:08,686 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-26 08:42:08,687 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-26 08:42:08,689 INFO    MainThread:22507 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-26 08:42:08,690 INFO    MainThread:22507 [wandb_init.py:_log_setup():521] Logging user logs to /Users/jasonokoro/Desktop/proyectos/nerf/wandb/run-20240426_084208-3aswvqd2/logs/debug.log
2024-04-26 08:42:08,691 INFO    MainThread:22507 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/jasonokoro/Desktop/proyectos/nerf/wandb/run-20240426_084208-3aswvqd2/logs/debug-internal.log
2024-04-26 08:42:08,692 INFO    MainThread:22507 [wandb_init.py:init():561] calling init triggers
2024-04-26 08:42:08,693 INFO    MainThread:22507 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'name': 'initial-run', 'batch_size': 4096, 'initial_lr': 0.0005, 'final_lr': 5e-05, 'num_epochs': 10, 'tn': 0, 'tf': 1, 'Nc': 64, 'Nf': 128}
2024-04-26 08:42:08,694 INFO    MainThread:22507 [wandb_init.py:init():611] starting backend
2024-04-26 08:42:08,694 INFO    MainThread:22507 [wandb_init.py:init():615] setting up manager
2024-04-26 08:42:08,715 INFO    MainThread:22507 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-04-26 08:42:08,718 INFO    MainThread:22507 [wandb_init.py:init():623] backend started and connected
2024-04-26 08:42:08,738 INFO    MainThread:22507 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-26 08:42:08,739 INFO    MainThread:22507 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-26 08:42:08,740 INFO    MainThread:22507 [wandb_init.py:init():715] updated telemetry
2024-04-26 08:42:08,824 INFO    MainThread:22507 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-26 08:42:11,633 WARNING MainThread:22507 [wandb_init.py:init():1203] interrupted
Traceback (most recent call last):
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 751, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonokoro/miniconda3/envs/nerf-env/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
